# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'mlcamera' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for react-native-firebase-mlkit
  pod 'Firebase/Analytics'
  pod 'Firebase/MLModelInterpreter'

  #optional - used to crop images
  pod 'react-native-image-editor', :path => '../node_modules/@react-native-community/image-editor'

end
# 